### ISSUE TITLE
tested on Ubuntu

### ISSUE THREAD

**Issue by TrackLiao** [chitosai/bilimini#10]
I've tested on Ubuntu 16.04 and here are the problem:
(It's okay to reply in Chinese)
1. it don't have the control panel, since you just tested on Mac and Windows10
2. when I first open it, it works fine. However, when I open it later, I shows Error that "Fail to bind globalShortcut"
3. The Boss key "Ctrl + E" not working
4. not in h5 UI

**Comment by chitosai** [comment]
我感觉这个程序应该不会有歪果仁用。。所以就用中文交流吧

1、你是说菜单吗？我在windows下没做菜单是因为windows程序的菜单是直接显示在程序上的，这样占用了一行空间，所以我故意没在windows下做菜单。
2、是不是你之前的程序没关闭？系统级的全局快捷键只能绑定一次，有两个程序要绑定同一个快捷键后一个程序就会失败
3、ctrl+e是windows下的快捷键，其他系统目前都是alt+w，不过linux下我确实没测试过
4、这是个bug，我在刚发布的1.0.4里已经尽量修复了，你pull一下再试试

**Comment by TrackLiao** [comment]
H5 这个问题在pull之后是解决， 现在的话
1。 视屏中展示的鼠标移动到顶端出现隐藏菜单这个功能没有运作
2。 因为没有菜单条，不能拖拽窗口，只能通过拉伸来移动
3。 按esc之后会返回普通网页模式
4。 alt+w / ctrl+e 都不起作用，目前这两个热键并没有被占用

**Comment by chitosai** [comment]
1、菜单栏的时我尝试在下个版本解决吧，可能是linux也不支持body:hover样式
2、同上
3、这个是b站自带播放器的行为，这我无法阻止啦（或者说阻止是不对的，因为目前只能通过退出全屏来主动切换分p
4、这我可能无法解决了，不清楚linux下全局快捷键有什么不同的用法。。并且手头没有带图形界面的linux

**Comment by TrackLiao** [comment]
1。窗口拖拽不方便这一类的问题我通过修改 openMainWindow()里默认的窗口尺寸和setPosition()定位到偏好位置效果还可以
2。 但是bindGlobalShortcut()这部分报错，查了一下相关文档，好象是使用的按键需要在main.js 里先初始化之后才能用
3。 最后一点是，全屏后右侧滚动条没有隐藏

**Comment by chitosai** [comment]
1、现在linux还还是不会出现topbar？我之前用js dirtycheck替换了之前css的实现，现在应该会显示topbar才对
2、绑定位置肯定是不会有问题的，可能linux下也不支持alt作为全局快捷键吧，下个版本我把linux也改成ctrl+e试试吧
3、这个我记下了，以后有时间看看，感谢反馈

**Comment by TrackLiao** [comment]
感谢积极更新
我查看了一下源码，虽然bindGlobalShortcut()里为linux设置成ctrl+e作为老板键，但是遗憾的是启动依旧提示Fail to bind globalShortcut。并且强制退出程序（ctrl+f4）时提示 main。js引用events。js 96：13，emitOne（），BrowserWindow。emit出错。
另一个比较严重的问题是任何页面下的视频缩略图有相当大几率点击无反应，需要刷新页面1～2次才生效
滚动条依旧坚挺

**Comment by chitosai** [comment]
全局快捷键现在可以自定义了，在ubuntu环境下换个快捷键试试？
至于滚动条...感觉我应该是无能为力了

**Comment by chitosai** [comment]
我在1.1.4中为了修复另外一个问题顺手对播放页面的滚动条做了下隐藏，可能会顺带解决你的问题？XD
