### ISSUE TITLE
在OS X中测试的问题

### ISSUE THREAD

**Issue by dbdb5269** [chitosai/bilimini#11]
1.在OS X启动后，可能不会请求到移动端，而是pc端界面。
2.启动后，会发生界面请求失败，是空白页。

**Comment by zhangsens** [comment]
T_T 我也是。
第一次npm start打开后正常的，点击一个视频后跳到pc首页。
关掉重开就是空开页。

**Comment by chitosai** [comment]
我在最近的1.0.4里尝试修复了这个bug，不知道你们用是1.0.4还是更早的版本？

**Comment by dbdb5269** [comment]
是在1.0.4下测试的

**Comment by chitosai** [comment]
唔，这就很尴尬了
你从菜单上点开 Debug -> Open Renderer Console，然后cmd+r刷新一下页面试试？

1.0.4之后我暂时想不到会是什么原因造成的

**Comment by qfdk** [comment]
目测是个缓存的问题，我尝试改user agent的时候也有这个bug 清理一下larary is里面的bilibilimini 临时文件 试一下  忘记名字了

**Comment by chitosai** [comment]
似乎前几个月electron依赖包更新后触发了未知bug，造成有一定几率无法正常打开页面，我至今也没搞清楚到底出了什么问题。
之后把electron依赖版本定死在1.6.2，似乎是没有问题了。
@dbdb5269 @zhangsens @qfdk
