### ISSUE TITLE
大大可以尝试弄成chrome插件，并上架(●'◡'●)

### ISSUE THREAD

**Issue by Arowa-Z** [chitosai/bilimini#12]

**Comment by chitosai** [comment]
感谢建议，google已经不再开放新chrome app的上传，并且推荐开发者都转去开发nw、electron等跨平台app，所以我们是顺应时代的潮流啦233

**Comment by chitosai** [comment]
顺便安利我的一款chrome插件
https://chrome.google.com/webstore/detail/fgadnbmmolnmbkbklpaojbogcopipopl

<del>绿色保护着你</del>
