### ISSUE TITLE
发送弹幕

### ISSUE THREAD

**Issue by shkey** [chitosai/bilimini#15]
能不能做个选项开启或者关闭在看视频的时候可以在下方发弹幕，现在我在看视频的时候想发弹幕的话，貌似没法弄啊，比如鼠标指针移出窗体外后，视频进度条下方的发送弹幕的框就出现了，但是我鼠标指针一移到窗体内进度条下方的弹幕发送框就隐藏了···虽说这个软件是做来划水的，但是在看视频的时候还是有发送弹幕的需求吧，还是说我的操作不对？

**Comment by chitosai** [comment]
我在昨天发布的v1.0.7上修复了这个问题，更新一下试试？

**Comment by shkey** [comment]
ok，可以发弹幕了。不过刚刚登录的时候又发现个问题，扫码登录后跳转回首页的时候是网页版，而不是H5版

**Comment by chitosai** [comment]
嗯，这个问题我注意到了，我会尽快解决的~感谢反馈
