### ISSUE TITLE
支持代理请求

### ISSUE THREAD

**Issue by qfdk** [chitosai/bilimini#17]
请求支持一下代理模式,不在大陆 不能愉快的玩耍, ss 回国通道需要代理的支持.

不知道有没有此计划,如果没有,我会尝试添加下这个奇葩的特性 :)

macos 登陆的地方会跳转到桌面版的登陆. (目测要设置一下浏览器的属性,可能设置成 iPhone 会解决这个问题)

**Comment by qfdk** [comment]
```JavaScript
wm.webContents.session.setProxy({proxyRules:"socks5://localhost :1080"}, function () {
    wm.loadURL('http://qfdk.me ');
});
```
昨天自己本地版本成功加代理 🚀 关键代码 配合ss使用 期待作者官方支持

**Comment by chitosai** [comment]
噗，感谢提供范例！
我这边最近会先处理拖了很久的窗口透明度需求，可能要晚点再处理这个需求了，sorry

**Comment by qfdk** [comment]
@chitosai 没事儿，慢慢来 :) 增加代理比改透明度 要简单一点儿，透明度那边

``` javascript
const {BrowserWindow} = require('electron')
let win = new BrowserWindow({transparent: true, frame: false})
win.show()
```
但愿能帮到你 :)

**Comment by chitosai** [comment]
卧槽，这个磨砂效果好棒，但是看了看文档好像兼容性很成问题啊。。不大敢用啊

**Comment by qfdk** [comment]
@chitosai 至少mac可以跑, 开一个mac的branch :)
windows 也可以，你编译出来之后他们就可以用了，虽然window的API 有点儿可能不靠谱，但是根据作者更新的频率 还是可以考虑的 :)

**Comment by qfdk** [comment]
已经支持代理 故关闭

**Comment by chitosai** [comment]
其实支持代理功能早就加上了，但是被#20提到的bug困扰了好久，终于能打出新版本了。
