### ISSUE TITLE
建议菜单添加一个关于

### ISSUE THREAD

**Issue by daorren** [chitosai/bilimini#21]
看到bilimini更新了，想看自己安装的版本，发现根本没地方看...

（作者什么的信息当然也可以加上去

---
补充：bilimini.app文件是可以看到版本的...

**Comment by chitosai** [comment]
关于是有的，顶部栏上的「？」就是，但是里面没有版本号。。失误，下个版本加上去

**Comment by chitosai** [comment]
关于中已增加版本号
