### ISSUE TITLE
【v1.1.8 win版本】 选择分p始终播放第一p

### ISSUE THREAD

**Issue by check321** [chitosai/bilimini#31]
![image](https://user-images.githubusercontent.com/11640912/51887246-f4923080-23cd-11e9-937d-2c23f2479694.png)

**Comment by ghwswywps** [comment]
我看了下应该是b站改了短链，
源码里index.js里
let url = `${videoUrlPrefix}${av[1]}/index_${pid}.html`;
改成
let url = `${videoUrlPrefix}${av[1]}/?p=${pid}`;
重新编译打包下就好了
不过目前还是有点不稳定凑合用，可惜我不是玩前端的。

**Comment by check321** [comment]
> 我看了下应该是b站改了短链，
> 源码里index.js里
> let url = `${videoUrlPrefix}${av[1]}/index_${pid}.html`;
> 改成
> let url = `${videoUrlPrefix}${av[1]}/?p=${pid}`;
> 重新编译打包下就好了
> 不过目前还是有点不稳定凑合用，可惜我不是玩前端的。

感谢指导，已提PR。
