### ISSUE TITLE
希望可以支持动态页面

### ISSUE THREAD

**Issue by superybq** [chitosai/bilimini#35]
[动态页面](https://t.bilibili.com/)
首页什么的内容太杂了,现在看B站基本上都是通过动态页看的,不过动态页好像没有手机版,所以估计没办法直接集成

**Comment by chitosai** [comment]
考虑过这个问题，我感觉自己实现的话以后维护起来成本太高了，b站一旦有变化我就得跟着升级，暂时应该不会做。感谢建议！
