### ISSUE TITLE
还是想要个视频动态页。。。

### ISSUE THREAD

**Issue by twowei** [chitosai/bilimini#39]
这个有做：https://github.com/canisminor1990/bilibili-client

**Comment by chitosai** [comment]
我去。。看了看图看了看代码，这真不是把我的代码重新写了一遍吗 -。-

回归正题，看了下代码，他的实现方式确实不错，而且挺简单的我居然没想到。。。有空我就加上，多谢建议！

**Comment by twowei** [comment]
感恩！

**Comment by chitosai** [comment]
更新了，你试试看，有问题喊我哈

**Comment by twowei** [comment]
收到了更新提示，不过有 Mac 的吗 🤣

**Comment by chitosai** [comment]
我现在没mac，在喊我朋友帮忙打包，等等

**Comment by chitosai** [comment]
@twowei 更新了

**Comment by twowei** [comment]
你康康要不要采用一下 哈哈哈
![image](https://user-images.githubusercontent.com/11190955/66565422-05b65280-eb95-11e9-9fef-93d9a27bc817.png)

**Comment by chitosai** [comment]
不必了。。现在的图标我挺喜欢的
