### ISSUE TITLE
macOS端已提交brew cask

### ISSUE THREAD

**Issue by Chandler-Lu** [chitosai/bilimini#41]
`brew cask install bilibilimini`
感谢作者开发～

**Comment by chitosai** [comment]
哦哦！非常感谢！

**Comment by chitosai** [comment]
@Chandler-Lu 哈喽，想问一下，brew的版本是怎么维护的？是我每次发布新版本后你会去那边手动发布新版本吗

**Comment by Chandler-Lu** [comment]
他们的 bot 会扫描 appcast 的发布信息，然后自动推送升级，当然这个更新可能存在延迟。先要手动发布的话，任何人都可以去给这个文件发 pr：https://github.com/Homebrew/homebrew-cask/blob/master/Casks/bilimini.rb

**Comment by chitosai** [comment]
喔。等于说只要我添加了新的release，并且附上了符合bilimini-#{version}-mac.zip规则的文件brew的源就会自动更新了是吗？

**Comment by Chandler-Lu** [comment]
对的～

**Comment by chitosai** [comment]
有点厉害！
好的我明白啦，感谢~
