### ISSUE TITLE
窗口大小问题

### ISSUE THREAD

**Issue by MQ-sheila** [chitosai/bilimini#45]
不知道双击到哪里了，导致窗口全屏，重新打开后是以全屏大小覆盖在屏幕上半段，但不知道怎么改回（删除重新解压无用）

2020/3/25 22:11:17 366 主线程：初始化；Platform：win32
2020/3/25 22:11:17 371 老板键：开始注册，isUpdate: false
2020/3/25 22:11:17 376 菜单：初始化结束
2020/3/25 22:11:17 484 主窗口：已创建
2020/3/25 22:11:17 376 主窗口：开始创建
2020/3/25 22:11:17 485 选p窗口：开始创建
2020/3/25 22:11:17 496 选p窗口：已创建
2020/3/25 22:11:17 496 设置窗口：开始创建
2020/3/25 22:11:17 507 设置窗口：已创建
2020/3/25 22:11:17 508 主线程：初始化流程结束
2020/3/25 22:11:17 372 老板键：注册成功
2020/3/25 22:11:17 372 菜单：初始化
2020/3/25 22:11:18 313 触发 did-get-redirect-request 事件，目标：https://m.bilibili.com/index.html
2020/3/25 22:11:19 054 触发 did-finish-load 事件，当前url是: https://m.bilibili.com/index.html
2020/3/25 22:11:20 348 更新用户设置：SET windowSizeDefault = [376,512]
2020/3/25 22:11:21 927 更新用户设置：SET windowSizeDefault = [376,512]
2020/3/25 22:11:23 532 更新用户设置：SET windowSizeDefault = [376,512]
2020/3/25 22:11:26 948 更新用户设置：SET windowSizeDefault = [376,512]

**Comment by chitosai** [comment]
最近的问题都是bv号引起的，我更新了1.4.1，试一下看看好了没有
