### ISSUE TITLE
mac10.15.4无法运行

### ISSUE THREAD

**Issue by coderykw** [chitosai/bilimini#47]
mac10.15.4无法运行 大佬求解

**Comment by chitosai** [comment]
具体是怎么个无法运行？能给个截图或者日志么

**Comment by Anr-C** [comment]
![image](https://user-images.githubusercontent.com/20478881/79060685-86781780-7cba-11ea-8cd3-07e277dfae65.png)

**Comment by chitosai** [comment]
@coderykw @Anr-C 

https://github.com/chitosai/bilimini/releases/download/v1.4.5/bilimini-1.4.5-mac.zip
我重新打了下包，你们试试，如果还无法运行的话就超出我的知识范围了

**Comment by Anr-C** [comment]
看来是没解了 not work~ 猝

**Comment by chitosai** [comment]
@Anr-C 那试试下那个dmg包看看能安装不？

**Comment by Anr-C** [comment]
> @Anr-C 那试试下那个dmg包看看能安装不？

很遗憾噢 一样的问题 你在回复的时候我就装了 然后尝试了重签名等常见错误处理手段 都不行 应该不属于软件内部错误 而像是程序入口错误

**Comment by chitosai** [comment]
@Anr-C 那真的超过我的能力范围了。。打包的过程是electron-builder自动做的，这我完全不懂。。

**Comment by Anr-C** [comment]
> @Anr-C 那真的超过我的能力范围了。。打包的过程是electron-builder自动做的，这我完全不懂。。

没事 等electron-builder更新吧 不过你也可以考虑研究下 哈哈哈

**Comment by lowking** [comment]
> > @Anr-C 那真的超过我的能力范围了。。打包的过程是electron-builder自动做的，这我完全不懂。。
> 
> 没事 等electron-builder更新吧 不过你也可以考虑研究下 哈哈哈

我电脑10.15.2的，你试试我fork下的看看
https://github.com/lowking/bilimini/releases

**Comment by Anr-C** [comment]
> > > @Anr-C 那真的超过我的能力范围了。。打包的过程是electron-builder自动做的，这我完全不懂。。
> > 
> > 
> > 没事 等electron-builder更新吧 不过你也可以考虑研究下 哈哈哈
> 
> 我电脑10.15.2的，你试试我fork下的看看
> https://github.com/lowking/bilimini/releases

还是无法打开噢 是不是有什么32位的库~

**Comment by Eurkidu** [comment]
1.4.5的dmg安装是可以打开的，zip解压的无法打开

可以打开应用程序，找到`bilimini`应用然后右键显示包内容->Contents->MacOS
查看下里面的bilimini图标是不是左上角显示一个exec的样子，如果是显示一个白板的，是无法打开的
我这边当前系统是10.15.4现在是可以正常运行1.4.5版本

不过播放器的弹幕在canvas模式下渲染的字体一直是宋体，有点小瑕疵，有空研究下

建议打不开的先删除然后在东西安装dmg的包
如果还是打不开，显示白板，可以参考下这个链接，或许有帮助
https://www.jianshu.com/p/45d9ab7fa921

**Comment by Anr-C** [comment]
> 1.4.5的dmg安装是可以打开的，zip解压的无法打开
> 
> 可以打开应用程序，找到`bilimini`应用然后右键显示包内容->Contents->MacOS
> 查看下里面的bilimini图标是不是左上角显示一个exec的样子，如果是显示一个白板的，是无法打开的
> 我这边当前系统是10.15.4现在是可以正常运行1.4.5版本
> 
> 不过播放器的弹幕在canvas模式下渲染的字体一直是宋体，有点小瑕疵，有空研究下
> 
> 建议打不开的先删除然后在东西安装dmg的包
> 如果还是打不开，显示白板，可以参考下这个链接，或许有帮助
> https://www.jianshu.com/p/45d9ab7fa921

感谢 我还一直没试过dmg dmg是可以的

 @lowking 建议把macdmg放第一位 zip要不要都行 我是直接下了第一个 没注意到还有权限问题

**Comment by chitosai** [comment]
> > 1.4.5的dmg安装是可以打开的，zip解压的无法打开
> > 可以打开应用程序，找到`bilimini`应用然后右键显示包内容->Contents->MacOS
> > 查看下里面的bilimini图标是不是左上角显示一个exec的样子，如果是显示一个白板的，是无法打开的
> > 我这边当前系统是10.15.4现在是可以正常运行1.4.5版本
> > 不过播放器的弹幕在canvas模式下渲染的字体一直是宋体，有点小瑕疵，有空研究下
> > 建议打不开的先删除然后在东西安装dmg的包
> > 如果还是打不开，显示白板，可以参考下这个链接，或许有帮助
> > https://www.jianshu.com/p/45d9ab7fa921
> 
> 感谢 我还一直没试过dmg dmg是可以的
> 
> @chitosai 建议把macdmg放第一位 zip要不要都行 我是直接下了第一个 没注意到还有权限问题

哎呀，一直没回。。
dmg和zip都是electron-builder自动创建出来的，然后现在release也是github-action自动做的，所以现在发布其实都是全自动的，我不太会去手动调整里面的文件。不过还是感谢反馈~
