### ISSUE TITLE
直播问题

### ISSUE THREAD

**Issue by wangqs97** [chitosai/bilimini#50]
作者你好，看直播的时候我发现有背景板的（比如LPL直播间）都只能打开电脑端网页界面。
<img width="732" alt="image" src="https://user-images.githubusercontent.com/55077238/78483766-0a8d4500-7779-11ea-84e3-4d24de09d8a8.png">
普通直播间没问题，但是大点的有背景板的直播间都会出现这个问题。

另外问一下怎么进自己关注主播的直播间呀，目前只能从首页下拉菜单中进入直播的首页。

**Comment by chitosai** [comment]
收到，官方直播间我会做下兼容。

至于关注的主播可能暂时就没办法了，类似这种功能我们自己实现出来的话B站老爱改api，后期维护成本太大了

**Comment by chitosai** [comment]
https://github.com/chitosai/bilimini/releases/tag/v1.4.3
好了 @wangqs97

**Comment by wangqs97** [comment]
> 收到，官方直播间我会做下兼容。
> 
> 至于关注的主播可能暂时就没办法了，类似这种功能我们自己实现出来的话B站老爱改api，后期维护成本太大了

刚看了一下，获取自己关注主播的API是`https://api.live.bilibili.com/relation/v1/Feed/getList`。因为我觉得摸鱼的时候看自己关注主播的直播还是很爽的。这个api如果稳定的话，您可以考虑一下。

**Comment by wangqs97** [comment]
> https://github.com/chitosai/bilimini/releases/tag/v1.4.3
> 好了 @wangqs97

请问mac版的发布吗，我是macos的

**Comment by chitosai** [comment]
> > 收到，官方直播间我会做下兼容。
> > 至于关注的主播可能暂时就没办法了，类似这种功能我们自己实现出来的话B站老爱改api，后期维护成本太大了
> 
> 刚看了一下，获取自己关注主播的API是`https://api.live.bilibili.com/relation/v1/Feed/getList`。因为我觉得摸鱼的时候看自己关注主播的直播还是很爽的。这个api如果稳定的话，您可以考虑一下。

自己做是不可能自己做的，这辈子都不会自己做的。。我现在只有一个分P功能是自己实现的，到现在为止起码改了3次api吧，长期维护太闹心了



> > https://github.com/chitosai/bilimini/releases/tag/v1.4.3
> > 好了 @wangqs97
> 
> 请问mac版的发布吗，我是macos的

这么不巧。。稍等一下吧，mac版是我朋友帮我打包的，发布了我再@你

**Comment by wangqs97** [comment]
233好吧，另外想问一下问什么要做分p呀，这儿不是能直接选吗。
<img width="959" alt="image" src="https://user-images.githubusercontent.com/55077238/78525266-3eb04680-7809-11ea-853e-12f99aa3f688.png">

**Comment by chitosai** [comment]
> 233好吧，另外想问一下问什么要做分p呀，这儿不是能直接选吗。
> <img alt="image" width="959" src="https://user-images.githubusercontent.com/55077238/78525266-3eb04680-7809-11ea-853e-12f99aa3f688.png">

一是因为以前B站没这功能，二是这个发现成本太高了，自己做也是被迫营业

**Comment by chitosai** [comment]
https://github.com/chitosai/bilimini/releases/tag/v1.4.3
@wangqs97 mac版也打好了

**Comment by wangqs97** [comment]
> https://github.com/chitosai/bilimini/releases/tag/v1.4.3
> @wangqs97 mac版也打好了

收到，感谢
