### ISSUE TITLE
就是一个白色的画面，什么都没有

### ISSUE THREAD

**Issue by nvnlv** [chitosai/bilimini#55]

**Comment by nvnlv** [comment]
![Uploading 1604022689316..jpg…]()

**Comment by nvnlv** [comment]
![1604022730120](https://user-images.githubusercontent.com/51050882/97650825-a8ec3b00-1a28-11eb-845f-57a68a040662.jpg)

**Comment by chitosai** [comment]
看来是electron发布了5.0版本，有两个breaking changes造成代码不可用了。因为你是electron升级之后才install的所以被你遇到了。。

但是然后我发现b站代码也有很大改动，好像很多功能都是失效了，我真是特么吐血。。等我有空的时候修一波再说吧。。。

**Comment by chitosai** [comment]
修复了，重新pull一下应该就正常了
