### ISSUE TITLE
这个项目，用的人多吗？

### ISSUE THREAD

**Issue by martinwithyou** [chitosai/bilimini#56]
这个项目，
用的人多吗？

**Comment by chitosai** [comment]
这是一个个人兴趣项目，没有多少用户

**Comment by martinwithyou** [comment]
> 这是一个个人兴趣项目，没有多少用户

我还没来得及看你的代码。。。。

**Comment by martinwithyou** [comment]
> 这是一个个人兴趣项目，没有多少用户

我觉得你的项目很有创意。。。。。

**Comment by chitosai** [comment]
> > 这是一个个人兴趣项目，没有多少用户
> 
> 我觉得你的项目很有创意。。。。。

谢谢~
