### ISSUE TITLE
B站直播页面显示效果异常

### ISSUE THREAD

**Issue by RRHRH** [chitosai/bilimini#61]
版本：1.5.2
系统：win10 20H2 64位 家庭版（近期有过系统升级）
问题：目前，在bilimini中打开B站直播页面时（从动态页面中打开，或直接输入网址跳转），软件无法自动调整画面，截图如下：
![0425](https://user-images.githubusercontent.com/44724232/115999614-04396780-a61f-11eb-9820-36f06d80e490.png)
卸载后重新安装bilimini，此问题依旧存在。
补充：之前春节期间使用此版本bilimini时未出现此问题，当时截图：
![0212](https://user-images.githubusercontent.com/44724232/116000207-d275d000-a621-11eb-80dd-8d104feb8a80.png)

**Comment by chitosai** [comment]
修复完毕，请更新到1.5.3
