### ISSUE TITLE
选集自动播放的时候，播放完后总是自动播放第一集，而不是自动播放下一集

### ISSUE THREAD

**Issue by itelite** [chitosai/bilimini#66]
选集自动播放的时候，播放完后总是自动播放第一集，而不是自动播放下一集。
具体版本bilimini-1.5.4-win
视频地址https://www.bilibili.com/video/BV19o4y1D71a

**Comment by chitosai** [comment]
我试了一下，似乎自动播放下一集这个功能本身是正常的，只是选p窗口的显示逻辑出错了，总是显示正在播放第一集。你发的这个视频每集开头都差不多，加上选p窗口有bug显示第一集，让你误以为一直在放第一集，其实是下一p没错。。。

**Comment by chitosai** [comment]
https://github.com/chitosai/bilimini/releases/tag/v1.5.5

修复了，试一下新版本
