### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by Robosky** [chitosai/bilimini#71]
目前 build/icon.png 采用的是64x64大小会导致在Linux下打包失败（需要512x512），可以麻烦作者更新一下嘛
P.S. 顺便问一下，这个项目用的是什么license呢？

**Comment by chitosai** [comment]
512x512的图标是什么玩法。。这都快正常屏幕的半个屏幕那么大了😅
这图是前几年顺手存的表情包，我看就算了吧，或者你fork之后自己找个AI放大工具试试

暂时没有license噢，没考虑过这问题。。
