### ISSUE TITLE
窗口透明度及置顶问题

### ISSUE THREAD

**Issue by RRHRH** [chitosai/bilimini#74]
设置窗口透明度时出现异常：在从“半透明”拖动到最右侧“完全不透明”、以及从“完全不透明”向左拖动时，软件会强制返回B站首页；
设置成“完全不透明”，关闭软件后重新打开，软件失去置顶显示效果（重要问题）。
1.5.6版bilimini
系统：win10 x64 20H2

**Comment by chitosai** [comment]
从有透明度到完全不透明时确实是经历了一个销毁原有窗口，重新创建不同窗口的过程，原因是完全不透明的窗口是有阴影的，而一旦有透明度就会切换成没有阴影的窗口。这个只能说设计如此了，非常不常用的功能没必要特地去做优化了。

至于失去置顶。。emmm，感觉也许是个偶发bug？我自己用这么久好像没遇到过，回头有时间我再看看

**Comment by RRHRH** [comment]
软件透明度一般很少调整，重建窗口对日常使用影响不大，可以接受。
至于失去置顶：之前我是在卸载旧版（1.5.4）后安装1.5.6版本，并出现软件更改透明度重开后不再置顶的问题。随后我就卸载装回了工作正常的旧版。现在使用1.5.6版的exe安装包覆盖升级旧版，反而无法复现之前的问题了（挠头问号脸）。只能说，如果没有其他使用者提交相似问题的话，也只好当成偶发bug了。如果之后找到了稳定复现的方法再说吧。
不管怎么说，非常感谢作者对我所提交问题的回复！
