### ISSUE TITLE
视频卡主无法播放

### ISSUE THREAD

**Issue by vurx** [chitosai/bilimini#75]
2022年1月25日，我像往常一样，冲了一杯cafe，坐在工位上，打开了bilimini，准备开始一天学习（摸鱼）之路，但是视频放不了了，卡住了，打开了浏览器的bilibili发现却是正常的。我很着急，已经半天没有学习了，我十分慌张。无奈之下，留下了此issues。

**Comment by dollarm** [comment]
> 我是过来看看这个问题解决了没有，貌似还没有

**Comment by dollarm** [comment]
> 2020年1月25日，我像往常一样，有一杯咖啡，坐在工位上，打开bilimini，准备开始一天学习（摸鱼）之路，但是冲视频放不了了，卡了，打开了浏览器的胆机发现却是正常的。我很着急，已经半天没有了，我很着急张张学习了。在下面，留下了这个问题。

我是过来看看问题解决了没有，可惜还没有

**Comment by chitosai** [comment]
啊这，不会吧上礼拜我还一切正常
不过这两天上班有点忙，抽不出足够时间来摸鱼修bug，等晚几天再看，稍等稍等（

**Comment by chitosai** [comment]
https://github.com/chitosai/bilimini/releases/tag/v1.5.7

更新了！

**Comment by vurx** [comment]
十分感谢！respect！
